# Generated by Django 4.0.4 on 2022-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(max_length=9)),
                ('cName', models.CharField(max_length=5)),
                ('cMajor', models.CharField(max_length=3)),
                ('cGrade', models.CharField(max_length=2)),
                ('ctime', models.CharField(default='', max_length=13)),
                ('cMail', models.EmailField(default='', max_length=35)),
                ('cStatus', models.CharField(blank=True, default='尚未進場', max_length=4)),
            ],
        ),
    ]
