# Generated by Django 4.0.4 on 2022-05-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ctime',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
